// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evhrjxbyhmjcmhgxceuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2aHJqeGJ5aG1qY21oZ3hjZXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODk0NDcsImV4cCI6MjA2NDY2NTQ0N30.qKwL5UA1CHr5nocqD1vXSsYPHkKIQRri6I2jNAL9oMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);